@server = http://localhost:4004

###   CHAT/GENERATE
POST {{server}}/chat/generate
Content-Type: application/json

{
   "conversation": {
      "id": "425f3d88-24cf-4ba2-8100-dd5fa9f32a83"
   },
   "prompt": "Me liste o nome dos produtos no banco de dados"
}

###   CONVERSATION
GET {{server}}/chat/Conversation
Content-Type: application/json

###   CONVERSATION
POST {{server}}/chat/Conversation
Content-Type: application/json

{
   "user": "gabriel.freire@lab2dev.com",
   "title": "How to develop a CAP API using SAP BTP BAS"
}

###   CONVERSATION
GET {{server}}/chat/Conversation?$expand=messages
Content-Type: application/json

###   CONVERSATION
DELETE {{server}}/chat/Conversation(baedffbe-3e98-49b3-944c-72a2b8d42b8f)
Content-Type: application/json

###   MESSAGES
GET {{server}}/chat/Message
Content-Type: application/json

###   MESSAGES
DELETE {{server}}/chat/Message(baedffbe-3e98-49b3-944c-72a2b8d42b8f)
Content-Type: application/json

###   MESSAGES
POST {{server}}/chat/Message
Content-Type: application/json

{
   "conversation_id": "499122f8-c2f4-4f23-9edc-f3a5474f62e4",
   "role": "user",
   "content": "How to develop a CAP API using SAP BTP BAS"
}
